package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/togo-framework/cli/internal/config"
	"github.com/togo-framework/cli/internal/ui"
)

// resolveProvider picks the deploy backend: --provider flag > target.Provider >
// the inline deploy.provider > DEPLOY_PROVIDER env. Empty / "ssh" / "vps" means
// the built-in rsync+ssh path (back-compat).
func resolveProvider(proj *config.Project, t config.DeployTarget, override string) string {
	p := override
	if p == "" {
		p = t.Provider
	}
	if p == "" {
		p = proj.Deploy.Provider
	}
	if p == "" {
		p = os.Getenv("DEPLOY_PROVIDER")
	}
	return strings.ToLower(strings.TrimSpace(p))
}

// isSSHProvider reports whether the provider should use the built-in rsync/ssh path.
func isSSHProvider(p string) bool {
	return p == "" || p == "ssh" || p == "vps" || p == "rsync"
}

// specFor builds the deploy.Spec fields from a resolved target.
func specFor(proj *config.Project, t config.DeployTarget) deploySpec {
	binary := t.Binary
	if binary == "" {
		if binary = proj.Name; binary == "" {
			binary = "app"
		}
	}
	env := map[string]string{}
	return deploySpec{
		App:      proj.Name,
		Dir:      proj.Root,
		BuildCmd: t.Build,
		Binary:   filepath.Join(proj.Root, ".togo", "deploy", binary),
		Image:    t.Image,
		Env:      env,
		Host:     t.Host,
		User:     t.User,
		Domain:   t.Domain,
		Region:   t.Region,
		Options:  t.Options,
	}
}

// deploySpec mirrors github.com/togo-framework/deploy.Spec so the CLI can render
// the runner and the dry-run plan without importing every provider plugin.
type deploySpec struct {
	App      string            `json:"App"`
	Dir      string            `json:"Dir"`
	BuildCmd string            `json:"BuildCmd"`
	Binary   string            `json:"Binary"`
	Image    string            `json:"Image"`
	Env      map[string]string `json:"Env"`
	Host     string            `json:"Host"`
	User     string            `json:"User"`
	Domain   string            `json:"Domain"`
	Region   string            `json:"Region"`
	Options  map[string]any    `json:"Options"`
}

// runPluginDeploy routes the deploy through the `deploy` plugin + its provider
// driver. The CLI can't statically import every provider (they self-register via
// init() and live in the project's module), so it resolves the driver from the
// project: it generates a tiny runner under .togo/deploy/runner that blank-imports
// deploy-<provider>, then `go run`s it inside the project module.
func runPluginDeploy(proj *config.Project, provider, op string, t config.DeployTarget, o deployOpts) error {
	spec := specFor(proj, t)
	pkg := "github.com/togo-framework/deploy-" + provider

	ui.Step("Deploy → provider %q  (op: %s)", provider, op)
	if o.dryRun {
		ui.Info("plan (dry-run):")
		ui.Step("1. provider : %s  (driver from %s)", provider, pkg)
		ui.Step("2. spec     : app=%s host=%s domain=%s image=%s region=%s", nz(spec.App), nz(spec.Host), nz(spec.Domain), nz(spec.Image), nz(spec.Region))
		if spec.BuildCmd != "" {
			ui.Step("3. build    : %s", spec.BuildCmd)
		}
		ui.Step("4. run      : deploy.Build(%q).%s(spec)  via  go run ./.togo/deploy/runner", provider, strings.Title(op))
		ui.Info("(remove --dry-run to execute; requires: togo install %s)", "togo-framework/deploy-"+provider)
		return nil
	}

	if err := ensureProviderInstalled(proj, provider, pkg); err != nil {
		return err
	}
	runnerDir, err := writeRunner(proj, provider, pkg)
	if err != nil {
		return err
	}

	payload, err := json.Marshal(map[string]any{"op": op, "spec": spec})
	if err != nil {
		return err
	}
	ui.Step("run: go run ./%s  (%s)", relTo(proj.Root, runnerDir), op)
	c := exec.Command("go", "run", "./"+filepath.ToSlash(relTo(proj.Root, runnerDir)))
	c.Dir = proj.Root
	c.Stdin = strings.NewReader(string(payload))
	c.Stdout, c.Stderr = os.Stdout, os.Stderr
	c.Env = os.Environ()
	if err := c.Run(); err != nil {
		return fmt.Errorf("deploy via provider %q failed: %w", provider, err)
	}
	ui.Success("Deployed %s via %s", proj.Name, provider)
	return nil
}

// ensureProviderInstalled checks the project's go.mod requires the provider plugin
// and points the user at `togo install` if it doesn't.
func ensureProviderInstalled(proj *config.Project, provider, pkg string) error {
	data, err := os.ReadFile(filepath.Join(proj.Root, "go.mod"))
	if err != nil {
		return fmt.Errorf("read go.mod: %w (run `togo deploy` from a togo project)", err)
	}
	if !strings.Contains(string(data), pkg) {
		return fmt.Errorf("deploy provider %q is not installed — run:\n  togo install togo-framework/deploy-%s", provider, provider)
	}
	return nil
}

const runnerTmpl = `// Code generated by ` + "`togo deploy`" + `. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/togo-framework/deploy"
	_ "{{.Pkg}}"
)

type req struct {
	Op   string      ` + "`json:\"op\"`" + `
	Spec deploy.Spec ` + "`json:\"spec\"`" + `
}

func main() {
	var r req
	if err := json.NewDecoder(os.Stdin).Decode(&r); err != nil {
		fmt.Fprintln(os.Stderr, "deploy runner: bad spec:", err)
		os.Exit(1)
	}
	d, err := deploy.Build("{{.Provider}}", nil)
	if err != nil {
		fmt.Fprintln(os.Stderr, "deploy runner:", err)
		os.Exit(1)
	}
	ctx := context.Background()
	switch r.Op {
	case "provision":
		res, err := d.Provision(ctx, r.Spec)
		report(res, err)
	case "destroy":
		if err := d.Destroy(ctx, r.Spec); err != nil {
			fmt.Fprintln(os.Stderr, "deploy runner:", err)
			os.Exit(1)
		}
		fmt.Println("destroyed", r.Spec.App)
	case "status":
		st, err := d.Status(ctx, r.Spec)
		if err != nil {
			fmt.Fprintln(os.Stderr, "deploy runner:", err)
			os.Exit(1)
		}
		fmt.Printf("healthy=%v %s\n", st.Healthy, st.Detail)
	default: // deploy
		res, err := d.Deploy(ctx, r.Spec)
		report(res, err)
	}
}

func report(res *deploy.Result, err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "deploy runner:", err)
		os.Exit(1)
	}
	if res != nil {
		if res.Message != "" {
			fmt.Println(res.Message)
		}
		if res.URL != "" {
			fmt.Println("URL:", res.URL)
		}
	}
}
`

// writeRunner renders the provider-specific runner program into the project module
// and returns its directory.
func writeRunner(proj *config.Project, provider, pkg string) (string, error) {
	dir := filepath.Join(proj.Root, ".togo", "deploy", "runner")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	tmpl, err := template.New("runner").Parse(runnerTmpl)
	if err != nil {
		return "", err
	}
	f, err := os.Create(filepath.Join(dir, "main.go"))
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tmpl.Execute(f, map[string]string{"Pkg": pkg, "Provider": provider}); err != nil {
		return "", err
	}
	return dir, nil
}

func nz(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
