package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/togo-framework/cli/internal/config"
	"github.com/togo-framework/cli/internal/ui"
)

// proxyProvider picks the dns backend: --provider flag > dns.provider >
// proxy.provider > DNS_DRIVER env. There is no built-in default — a provider
// must be configured (the `log` driver is the plugin's own safe no-op default).
func proxyProvider(proj *config.Project, override string) string {
	p := override
	if p == "" {
		p = proj.DNS.Provider
	}
	if p == "" {
		p = proj.Proxy.Provider
	}
	if p == "" {
		p = os.Getenv("DNS_DRIVER")
	}
	return strings.ToLower(strings.TrimSpace(p))
}

// proxyZone resolves the DNS zone for record ops: --zone flag > dns.zone > proxy.zone.
func proxyZone(proj *config.Project, override string) string {
	if override != "" {
		return override
	}
	if proj.DNS.Zone != "" {
		return proj.DNS.Zone
	}
	return proj.Proxy.Zone
}

// proxyReq is the JSON payload handed to the generated runner over stdin. The
// nested maps use the dns plugin's exported field names (Record/ProxyHost/Route
// have no json tags) so they decode straight into the plugin structs.
type proxyReq struct {
	Op     string         `json:"op"`
	Zone   string         `json:"zone"`
	Record map[string]any `json:"record"`
	Host   map[string]any `json:"host"`
	Route  map[string]any `json:"route"`
	ID     string         `json:"id"`
}

// runProxyOp routes a proxy operation through the `dns` plugin + its provider
// driver. Like `togo deploy`, the CLI can't statically import every dns provider
// (they self-register via init() and live in the project's module), so it
// generates a tiny runner under .togo/proxy/runner that blank-imports
// dns-<provider>, then `go run`s it inside the project module.
func runProxyOp(proj *config.Project, provider, plan string, req proxyReq, dryRun bool) error {
	if provider == "" {
		return fmt.Errorf("no dns provider configured — set dns.provider in togo.yaml (cloudflare|npm|caddy|kong) or pass --provider")
	}
	pkg := "github.com/togo-framework/dns-" + provider

	ui.Step("Proxy → provider %q  (op: %s)", provider, req.Op)
	if dryRun {
		ui.Info("plan (dry-run):")
		ui.Step("1. provider : %s  (driver from %s)", provider, pkg)
		ui.Step("2. %s", plan)
		ui.Step("3. run      : dns.Build(%q).%s  via  go run ./.togo/proxy/runner", provider, opMethod(req.Op))
		ui.Info("(remove --dry-run to execute; requires: togo install togo-framework/dns-%s)", provider)
		return nil
	}

	if err := ensureDNSProviderInstalled(proj, provider, pkg); err != nil {
		return err
	}
	runnerDir, err := writeProxyRunner(proj, provider, pkg)
	if err != nil {
		return err
	}
	payload, err := json.Marshal(req)
	if err != nil {
		return err
	}
	ui.Step("run: go run ./%s  (%s)", relTo(proj.Root, runnerDir), req.Op)
	c := exec.Command("go", "run", "./"+filepath.ToSlash(relTo(proj.Root, runnerDir)))
	c.Dir = proj.Root
	c.Stdin = strings.NewReader(string(payload))
	c.Stdout, c.Stderr = os.Stdout, os.Stderr
	c.Env = os.Environ()
	if err := c.Run(); err != nil {
		return fmt.Errorf("proxy op %q via provider %q failed: %w", req.Op, provider, err)
	}
	return nil
}

// opMethod maps an op to the Service method name (for the dry-run plan line).
func opMethod(op string) string {
	switch op {
	case "record.upsert":
		return "UpsertRecord(zone, record)"
	case "record.list":
		return "ListRecords(zone)"
	case "record.delete":
		return "DeleteRecord(zone, id)"
	case "host.upsert":
		return "UpsertProxyHost(host)"
	case "host.delete":
		return "DeleteProxyHost(id)"
	case "route.upsert":
		return "UpsertRoute(route)"
	case "route.delete":
		return "DeleteRoute(id)"
	}
	return op
}

// ensureDNSProviderInstalled checks the project's go.mod requires the dns provider
// plugin and points the user at `togo install` if it doesn't.
func ensureDNSProviderInstalled(proj *config.Project, provider, pkg string) error {
	data, err := os.ReadFile(filepath.Join(proj.Root, "go.mod"))
	if err != nil {
		return fmt.Errorf("read go.mod: %w (run `togo proxy` from a togo project)", err)
	}
	if !strings.Contains(string(data), pkg) {
		return fmt.Errorf("dns provider %q is not installed — run:\n  togo install togo-framework/dns-%s", provider, provider)
	}
	return nil
}

const proxyRunnerTmpl = `// Code generated by ` + "`togo proxy`" + `. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/togo-framework/dns"
	_ "{{.Pkg}}"
)

type req struct {
	Op     string        ` + "`json:\"op\"`" + `
	Zone   string        ` + "`json:\"zone\"`" + `
	Record dns.Record    ` + "`json:\"record\"`" + `
	Host   dns.ProxyHost ` + "`json:\"host\"`" + `
	Route  dns.Route     ` + "`json:\"route\"`" + `
	ID     string        ` + "`json:\"id\"`" + `
}

func main() {
	var r req
	if err := json.NewDecoder(os.Stdin).Decode(&r); err != nil {
		die("bad request: " + err.Error())
	}
	s, err := dns.Build("{{.Provider}}", nil)
	if err != nil {
		die(err.Error())
	}
	ctx := context.Background()
	switch r.Op {
	case "record.upsert":
		id, err := s.UpsertRecord(ctx, r.Zone, r.Record)
		check(err)
		fmt.Println("✓ record", r.Record.Type, r.Record.Name, "→", id)
	case "record.list":
		recs, err := s.ListRecords(ctx, r.Zone)
		check(err)
		if len(recs) == 0 {
			fmt.Println("(no records)")
			return
		}
		for _, rec := range recs {
			fmt.Printf("%-6s %-24s %-34s %s\n", rec.Type, rec.Name, rec.Content, rec.ID)
		}
	case "record.delete":
		id := r.ID
		if id == "" {
			recs, err := s.ListRecords(ctx, r.Zone)
			check(err)
			for _, rec := range recs {
				if rec.Name == r.Record.Name && rec.Type == r.Record.Type {
					id = rec.ID
					break
				}
			}
			if id == "" {
				die(fmt.Sprintf("no %s record %q in zone %s", r.Record.Type, r.Record.Name, r.Zone))
			}
		}
		check(s.DeleteRecord(ctx, r.Zone, id))
		fmt.Println("✓ deleted record", id)
	case "host.upsert":
		id, err := s.UpsertProxyHost(ctx, r.Host)
		check(err)
		fmt.Println("✓ proxy host", r.Host.Domain, "→", r.Host.Upstream, "("+id+")")
	case "host.delete":
		check(s.DeleteProxyHost(ctx, r.ID))
		fmt.Println("✓ deleted proxy host", r.ID)
	case "route.upsert":
		id, err := s.UpsertRoute(ctx, r.Route)
		check(err)
		fmt.Println("✓ route", r.Route.Domain+r.Route.Path, "→", r.Route.Upstream, "("+id+")")
	case "route.delete":
		check(s.DeleteRoute(ctx, r.ID))
		fmt.Println("✓ deleted route", r.ID)
	default:
		die("unknown op " + r.Op)
	}
}

func check(err error) {
	if err != nil {
		die(err.Error())
	}
}

func die(msg string) {
	fmt.Fprintln(os.Stderr, "proxy runner:", msg)
	os.Exit(1)
}
`

// writeProxyRunner renders the provider-specific runner program into the project
// module and returns its directory.
func writeProxyRunner(proj *config.Project, provider, pkg string) (string, error) {
	dir := filepath.Join(proj.Root, ".togo", "proxy", "runner")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	tmpl, err := template.New("proxyrunner").Parse(proxyRunnerTmpl)
	if err != nil {
		return "", err
	}
	f, err := os.Create(filepath.Join(dir, "main.go"))
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tmpl.Execute(f, map[string]string{"Pkg": pkg, "Provider": provider}); err != nil {
		return "", err
	}
	return dir, nil
}
