package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/togo-framework/cli/internal/config"
	"github.com/togo-framework/cli/internal/ui"
)

// tunnelProvider picks the tunnel backend: --provider flag > tunnel.provider >
// TUNNEL_DRIVER env. There's no built-in default — a provider must be configured
// (the plugin's own `log` driver is the safe no-op default inside the app).
func tunnelProvider(proj *config.Project, override string) string {
	p := override
	if p == "" {
		p = proj.Tunnel.Provider
	}
	if p == "" {
		p = os.Getenv("TUNNEL_DRIVER")
	}
	return strings.ToLower(strings.TrimSpace(p))
}

// tunnelReq is the JSON payload handed to the generated runner over stdin.
type tunnelReq struct {
	Op   string `json:"op"`   // start | status | stop
	Addr string `json:"addr"` // local address for start
}

// runTunnelOp routes a tunnel operation through the `tunnel` plugin + its provider
// driver. Like `togo proxy`/`togo deploy`, the CLI can't statically import every
// tunnel provider (they self-register via init() and live in the project's
// module), so it generates a tiny runner under .togo/tunnel/runner that
// blank-imports tunnel-<provider>, then `go run`s it inside the project module.
func runTunnelOp(proj *config.Project, provider string, req tunnelReq, dryRun bool) error {
	if provider == "" {
		return fmt.Errorf("no tunnel provider configured — set tunnel.provider in togo.yaml (cloudflare|ngrok|tailscale|frp) or pass --provider")
	}
	pkg := "github.com/togo-framework/tunnel-" + provider

	ui.Step("Tunnel → provider %q  (op: %s)", provider, req.Op)
	if dryRun {
		ui.Info("plan (dry-run):")
		ui.Step("1. provider : %s  (driver from %s)", provider, pkg)
		switch req.Op {
		case "start":
			ui.Step("2. start    : tunnel.Build(%q).Start(ctx, %q) → prints the public URL (blocks; Ctrl-C to stop)", provider, req.Addr)
		case "status":
			ui.Step("2. status   : tunnel.Build(%q).Status(ctx)", provider)
		case "stop":
			ui.Step("2. stop     : tunnel.Build(%q).Stop(ctx)", provider)
		}
		ui.Step("3. run      : go run ./.togo/tunnel/runner")
		ui.Info("(remove --dry-run to execute; requires: togo install togo-framework/tunnel-%s)", provider)
		return nil
	}

	if err := ensureTunnelProviderInstalled(proj, provider, pkg); err != nil {
		return err
	}
	runnerDir, err := writeTunnelRunner(proj, provider, pkg)
	if err != nil {
		return err
	}
	payload, err := json.Marshal(req)
	if err != nil {
		return err
	}
	if req.Op == "start" {
		ui.Info("starting tunnel via %q — press Ctrl-C to stop", provider)
	}
	c := exec.Command("go", "run", "./"+filepath.ToSlash(relTo(proj.Root, runnerDir)))
	c.Dir = proj.Root
	c.Stdin = strings.NewReader(string(payload))
	c.Stdout, c.Stderr = os.Stdout, os.Stderr
	c.Env = os.Environ()
	if err := c.Run(); err != nil {
		// Ctrl-C of a `start` tunnel exits non-zero via the signal — not an error to surface loudly.
		if req.Op == "start" {
			return nil
		}
		return fmt.Errorf("tunnel %q via provider %q failed: %w", req.Op, provider, err)
	}
	return nil
}

// ensureTunnelProviderInstalled checks the project's go.mod requires the tunnel
// provider plugin and points the user at `togo install` if it doesn't.
func ensureTunnelProviderInstalled(proj *config.Project, provider, pkg string) error {
	data, err := os.ReadFile(filepath.Join(proj.Root, "go.mod"))
	if err != nil {
		return fmt.Errorf("read go.mod: %w (run `togo tunnel` from a togo project)", err)
	}
	if !strings.Contains(string(data), pkg) {
		return fmt.Errorf("tunnel provider %q is not installed — run:\n  togo install togo-framework/tunnel-%s", provider, provider)
	}
	return nil
}

const tunnelRunnerTmpl = `// Code generated by ` + "`togo tunnel`" + `. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/togo-framework/tunnel"
	_ "{{.Pkg}}"
)

type req struct {
	Op   string ` + "`json:\"op\"`" + `
	Addr string ` + "`json:\"addr\"`" + `
}

func main() {
	var r req
	if err := json.NewDecoder(os.Stdin).Decode(&r); err != nil {
		die("bad request: " + err.Error())
	}
	s, err := tunnel.Build("{{.Provider}}", nil)
	if err != nil {
		die(err.Error())
	}
	switch r.Op {
	case "start":
		ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer stop()
		url, err := s.Start(ctx, r.Addr)
		check(err)
		fmt.Println("✓ tunnel up via {{.Provider}}")
		fmt.Println("  " + r.Addr + "  →  " + url)
		fmt.Println("  press Ctrl-C to stop")
		<-ctx.Done()
		fmt.Println("\nstopping tunnel…")
		_ = s.Stop(context.Background())
	case "status":
		st, err := s.Status(context.Background())
		check(err)
		if st.Running {
			fmt.Println("running via", st.Driver, "→", st.URL)
		} else {
			fmt.Println("not running (driver:", st.Driver+")")
		}
	case "stop":
		check(s.Stop(context.Background()))
		fmt.Println("✓ tunnel stopped")
	default:
		die("unknown op " + r.Op)
	}
}

func check(err error) {
	if err != nil {
		die(err.Error())
	}
}

func die(msg string) {
	fmt.Fprintln(os.Stderr, "tunnel runner:", msg)
	os.Exit(1)
}
`

// writeTunnelRunner renders the provider-specific runner program into the project
// module and returns its directory.
func writeTunnelRunner(proj *config.Project, provider, pkg string) (string, error) {
	dir := filepath.Join(proj.Root, ".togo", "tunnel", "runner")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	tmpl, err := template.New("tunnelrunner").Parse(tunnelRunnerTmpl)
	if err != nil {
		return "", err
	}
	f, err := os.Create(filepath.Join(dir, "main.go"))
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := tmpl.Execute(f, map[string]string{"Pkg": pkg, "Provider": provider}); err != nil {
		return "", err
	}
	return dir, nil
}
